name: "Run tests"

on: 
  push:
    branches:
      - "main"
  pull_request: 
    branches:
      - "main"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

